version: '2'
services:
  btpproject-app:
    image: btpproject
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://btpproject-mysql:3306/btpproject?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://btpproject-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://btpproject-elasticsearch:9200
    ports:
      - 8080:8080
  btpproject-mysql:
    extends:
      file: mysql.yml
      service: btpproject-mysql
  btpproject-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: btpproject-elasticsearch
